version: '3.5'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - db
    networks:
      - default
    volumes:
      - "./backend/resources:/backend/resources"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - 3001:3000
    volumes:
      - "./frontend:/frontend"
      - "/frontend/node_modules"
    environment:
      CHOKIDAR_USEPOLLING: "true"
  db:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5436:5432
    volumes:
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./data:/var/lib/postgresql/data
  proxy:
    container_name: nginx
    build: 
      context: nginx/
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./nginx:/etc/nginx/
    ports:
      - 80:80
