version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    working_dir: /backend
    restart: on-failure
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8000 --reload'
    depends_on:
      - db
    networks:
      - default
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes:
      - "./frontend:/frontend"
      - "/frontend/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_SITE_KEY=6LfKXLgkAAAAAH2yOQPNzkpKEe9J4H8eLqpXKh54
  db:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5436:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  proxy:
    container_name: nginx
    build: 
      context: nginx/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - "backend"
      - "frontend"
    volumes:
      - ./nginx:/etc/nginx/
    ports:
      - 80:80
