version: '3.5'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  db:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5436:5432
    volumes:
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./data:/var/lib/postgresql/data
