name: CI
on:
  push:
    branches:
      - develop
jobs:
  run-tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v1
        with:
          python-version: 3.11
          architecture: 'x64'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Tests
        run: |
          cd ./backend/test
          pytest tests.py